# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=12)),
                ('street', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=2, null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_label', models.URLField(blank=True, null=True)),
                ('shipping_id', models.CharField(blank=True, max_length=200, null=True)),
                ('rate_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'RE', b'Recieved'), (b'AS', b'Assigned'), (b'TR', b'In Transit'), (b'DE', b'Delivered'), (b'PD', b'Paid')], default=b'RE', max_length=2)),
                ('service', models.CharField(choices=[(b'EX', b'Express'), (b'SD', b'Same Day'), (b'ND', b'Next Day')], default=None, max_length=2)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to=settings.AUTH_USER_MODEL)),
                ('dropoff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='api.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Parcel'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='api.Address'),
        ),
    ]
