# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160205_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='contact_number',
            new_name='number',
        ),
    ]
