# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160209_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='phone',
        ),
    ]
